/*
 * Copyright (c) 2026 Christian Hansen <chansen@cpan.org>
 * <https://github.com/chansen/c-emoji>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/* Unicode Character Database predicates for emoji property detection (UTS #51 v17.0.0).
 *
 * emoji_ucd_is_emoji() covers all 1438 Emoji-property codepoints,
 * emoji_ucd_is_modifier_base() covers all 134 Emoji_Modifier_Base codepoints,
 * and emoji_ucd_is_presentation() covers all 1219 Emoji_Presentation codepoints,
 * all via two-level compressed tries.
 *
 * Note that the Emoji property does not imply emoji presentation.  Digits,
 * # and * are Emoji but text-default; emoji_ucd_is_presentation() resolves
 * the ambiguity for codepoints where no variation selector was seen.
 */
#ifndef EMOJI_UCD_H
#define EMOJI_UCD_H
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// U+0023 NUMBER SIGN, U+002A ASTERISK, U+0030..U+0039 DIGIT ONE..NINE,
static inline bool emoji_ucd_is_keycap_base(uint32_t cp) {
  return cp == 0x0023 || cp == 0x002A || (cp >= 0x0030 && cp <= 0x0039);
}

// U+20E3 COMBINING ENCLOSING KEYCAP
static inline bool emoji_ucd_is_enclosing_keycap(uint32_t cp) {
  return cp == 0x20E3;
}

// U+1F3F4 WAVING BLACK FLAG
static inline bool emoji_ucd_is_tag_base(uint32_t cp) {
  return cp == 0x1F3F4;
}

// U+E0020 TAG SPACE to U+E007E TAG TILDE
static inline bool emoji_ucd_is_tag_spec(uint32_t cp) {
  return cp >= 0xE0020 && cp <= 0xE007E;
}

// U+E007F CANCEL TAG
static inline bool emoji_ucd_is_tag_term(uint32_t cp) {
  return cp == 0xE007F;
}

// U+FE0E VARIATION SELECTOR-15
static inline bool emoji_ucd_is_text_presentation_selector(uint32_t cp) {
  return cp == 0xFE0E;
}

// U+FE0F VARIATION SELECTOR-16
static inline bool emoji_ucd_is_emoji_presentation_selector(uint32_t cp) {
  return cp == 0xFE0F;
}

// REGIONAL INDICATOR SYMBOL LETTER A..Z
static inline bool emoji_ucd_is_regional_indicator(uint32_t cp) {
  return cp >= 0x1F1E6 && cp <= 0x1F1FF;
}

// EMOJI MODIFIER FITZPATRICK TYPE 1-6
static inline bool emoji_ucd_is_modifier(uint32_t cp) {
  return cp >= 0x1F3FB && cp <= 0x1F3FF;
}

/* DO NOT EDIT - Generated by ucdgen
 * Source: ucd/emoji/emoji-data.txt
 * Date:   Thu Mar 26 12:00:13 2026
 * Property: Emoji_Modifier_Base
 * Type: Binary property
 * Codepoints in set: 134
 * Range: U+261D..U+1FAF8
 * 
 * Trie structure:
 *   idx0: uint8_t[136] = 136 bytes
 *   idx1: uint8_t[96] = 96 bytes
 *   data: uint8_t[288] = 288 bytes (bitset: 2304 bits)
 *   Total: 520 bytes (block=256, page=32)
 * 
 * Value distribution:
 *   Value   Codepoints    Span
 *   Yes            134    U+261D..U+1FAF8
 *   No         1113978    U+0000..U+10FFFF
 *   ----       1114112 (universe)
 */

static const uint8_t emoji_ucd_is_modifier_base_idx0[136] = {
  0, 1, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 2,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0
};

static const uint8_t emoji_ucd_is_modifier_base_idx1[96] = {
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 1, 2,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 3, 4, 5, 6, 0,
  0, 7, 8, 0, 0, 0, 0, 0
};

static const uint8_t emoji_ucd_is_modifier_base_data[288] = {
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,  32,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   2,
    0,  60,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
   32,   0,   0,   0,   0,   0,   0,   0,
  156,  28,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
  204, 255,   1,   0, 192, 255, 255,  17,
  238, 128,   2,   0,   0,   4,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,  48,   4,
    0,   0,  97,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
  224, 248,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   8,   0, 112,   0,
    1,  16,   0,   0,   0,   0,   0,   0,
    0, 144,   0, 255,  64,   0, 255, 115,
    0,   0,   0,   0,   0,   0, 128,   0,
    0,   0,   0,   0,   0,   0,  96,  11,
    0, 224, 254,  63,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
   56,   0,   0,   0,   0,   0, 255,   1
};

#define EMOJI_UCD_IS_MODIFIER_BASE_INDEX_SHIFT 8
#define EMOJI_UCD_IS_MODIFIER_BASE_INDEX_MASK ((1u << EMOJI_UCD_IS_MODIFIER_BASE_INDEX_SHIFT) - 1)
#define EMOJI_UCD_IS_MODIFIER_BASE_BLOCK_SIZE  256
#define EMOJI_UCD_IS_MODIFIER_BASE_BLOCK_SHIFT 8
#define EMOJI_UCD_IS_MODIFIER_BASE_BLOCK_MASK (EMOJI_UCD_IS_MODIFIER_BASE_BLOCK_SIZE - 1)
#define EMOJI_UCD_IS_MODIFIER_BASE_PAGE_SIZE   32
#define EMOJI_UCD_IS_MODIFIER_BASE_PAGE_SHIFT  5
#define EMOJI_UCD_IS_MODIFIER_BASE_PAGE_MASK  (EMOJI_UCD_IS_MODIFIER_BASE_PAGE_SIZE - 1)

static inline bool emoji_ucd_is_modifier_base(uint32_t cp) {
  uint32_t page = (cp >> (EMOJI_UCD_IS_MODIFIER_BASE_BLOCK_SHIFT + EMOJI_UCD_IS_MODIFIER_BASE_PAGE_SHIFT)) & EMOJI_UCD_IS_MODIFIER_BASE_INDEX_MASK;
  uint32_t off1 = (cp >> EMOJI_UCD_IS_MODIFIER_BASE_BLOCK_SHIFT) & EMOJI_UCD_IS_MODIFIER_BASE_PAGE_MASK;
  uint32_t off2 = cp & EMOJI_UCD_IS_MODIFIER_BASE_BLOCK_MASK;

  uint32_t i0 = emoji_ucd_is_modifier_base_idx0[page];
  uint32_t i1 = emoji_ucd_is_modifier_base_idx1[(i0 << EMOJI_UCD_IS_MODIFIER_BASE_PAGE_SHIFT) + off1];

  uint32_t data_idx = (i1 << EMOJI_UCD_IS_MODIFIER_BASE_BLOCK_SHIFT) + off2;
  return (emoji_ucd_is_modifier_base_data[data_idx >> 3] >> (data_idx & 7)) & 1;
}

/* DO NOT EDIT - Generated by ucdgen
 * Source: ucd/emoji/emoji-data.txt
 * Date:   Sat Feb  7 14:52:41 2026
 * Property: Emoji
 * Type: Binary property
 * Codepoints in set: 1438
 * Range: U+0023..U+1FAF8
 *
 * Trie structure:
 *   idx0: uint8_t[136] = 136 bytes
 *   idx1: uint8_t[256] = 256 bytes
 *   data: uint8_t[560] = 560 bytes (bitset: 4480 bits)
 *   Total: 952 bytes (block=128, page=64)
 *
 * Value distribution:
 *   Value   Codepoints    Span
 *   Yes           1438    U+0023..U+1FAF8
 *   No         1112674    U+0000..U+10FFFF
 *   ----       1114112 (universe)
 */

static const uint8_t emoji_ucd_is_emoji_idx0[136] = {
  0, 1, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 3,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2
};

static const uint8_t emoji_ucd_is_emoji_idx1[256] = {
   0,  1,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   3,  2,  4,  5,  2,  2,  6,  7,
   2,  8,  2,  9, 10, 11, 12, 13,
   2,  2, 14,  2,  2,  2, 15,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
  16,  2,  2,  2,  2, 17,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2,
  18, 19, 20, 21, 22,  2, 23, 24,
  25, 26, 27, 28, 29, 30,  2, 31,
   2,  2, 32, 25, 33, 34,  2,  2,
   2,  2,  2,  2,  2,  2,  2,  2
};

static const uint8_t emoji_ucd_is_emoji_data[560] = {
    0,   0,   0,   0,   8,   4, 255,   3,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,  66,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,  16,
    0,   2,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   4,   0,   0,   2,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0, 240,   3,   0,   6,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,  12,   0,   1,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0, 128,   0,   0,   0, 254,  15,   7,
    0,   0,   0,   0,   0,   0,   0,   0,
    4,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,  12,  64,   0,
    1,   0,   0,   0,   0,   0,   0, 120,
   31,  64,  50,  33,  77, 196,   0,   7,
    5, 255,  15, 128, 105,   1,   0, 200,
    0,   0, 252,  26, 131,  12,   3,  96,
   48, 193,  26,   0,   0,   6, 191,  39,
   36, 191,  84,  32,   2,   1,  24,   0,
  144,  80, 184,   0,  24,   0,   0,   0,
    0,   0, 224,   0,   2,   0,   1, 128,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,  48,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
  224,   0,   0,  24,   0,   0,   0,   0,
    0,   0,  33,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   1,  32,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0, 128,   2,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
   16,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0, 128,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   3, 192,
    0,  64, 254,   7,   0,   0,   0,   0,
    0,   0,   0,   0, 192, 255, 255, 255,
    6,   0,   0,   4,   0, 128, 252,   7,
    0,   0,   3,   0,   0,   0,   0,   0,
  255, 255, 255, 255, 243, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 255, 255,
  255, 255, 207, 206, 255, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 185, 255,
  255, 255, 255, 255, 255, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 255, 191,
  255, 255, 255, 255, 255, 255, 255,  63,
    0, 126, 255, 255, 255, 128, 249,   7,
  128,  60,  97,   0,  48,   1,   6,  16,
   28,   0,  14, 112,  10, 129,   8, 252,
  255, 255, 255, 255, 255, 255, 255, 255,
  255, 255,   0,   0,   0,   0,   0,   0,
  255, 255, 255, 255, 255, 255, 255, 255,
   63, 248, 231, 241,  63,  26, 249,  31,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0, 255,  15,   1,   0,
    0, 240, 255, 255, 255, 255, 255, 247,
  191, 255, 255, 255, 255, 255, 255, 255,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0, 255,  31,
  255, 199, 255, 255, 255, 255, 255, 255,
  127, 225, 255, 159, 255, 135, 255,   1
};

#define EMOJI_UCD_IS_EMOJI_INDEX_SHIFT 8
#define EMOJI_UCD_IS_EMOJI_INDEX_MASK ((1u << EMOJI_UCD_IS_EMOJI_INDEX_SHIFT) - 1)
#define EMOJI_UCD_IS_EMOJI_BLOCK_SIZE  128
#define EMOJI_UCD_IS_EMOJI_BLOCK_SHIFT 7
#define EMOJI_UCD_IS_EMOJI_BLOCK_MASK (EMOJI_UCD_IS_EMOJI_BLOCK_SIZE - 1)
#define EMOJI_UCD_IS_EMOJI_PAGE_SIZE   64
#define EMOJI_UCD_IS_EMOJI_PAGE_SHIFT  6
#define EMOJI_UCD_IS_EMOJI_PAGE_MASK  (EMOJI_UCD_IS_EMOJI_PAGE_SIZE - 1)

static inline bool emoji_ucd_is_emoji(uint32_t cp) {
  uint32_t page = (cp >> (EMOJI_UCD_IS_EMOJI_BLOCK_SHIFT + EMOJI_UCD_IS_EMOJI_PAGE_SHIFT)) & EMOJI_UCD_IS_EMOJI_INDEX_MASK;
  uint32_t off1 = (cp >> EMOJI_UCD_IS_EMOJI_BLOCK_SHIFT) & EMOJI_UCD_IS_EMOJI_PAGE_MASK;
  uint32_t off2 = cp & EMOJI_UCD_IS_EMOJI_BLOCK_MASK;

  uint32_t i0 = emoji_ucd_is_emoji_idx0[page];
  uint32_t i1 = emoji_ucd_is_emoji_idx1[(i0 << EMOJI_UCD_IS_EMOJI_PAGE_SHIFT) + off1];

  uint32_t data_idx = (i1 << EMOJI_UCD_IS_EMOJI_BLOCK_SHIFT) + off2;
  return (emoji_ucd_is_emoji_data[data_idx >> 3] >> (data_idx & 7)) & 1;
}

/* DO NOT EDIT - Generated by ucdgen
 * Source: ucd/emoji/emoji-data.txt
 * Date:   Fri Mar 27 00:35:51 2026
 * Property: Emoji_Presentation
 * Type: Binary property
 * Codepoints in set: 1219
 * Range: U+231A..U+1FAF8
 * 
 * Trie structure:
 *   idx0: uint8_t[136] = 136 bytes
 *   idx1: uint8_t[192] = 192 bytes
 *   data: uint8_t[416] = 416 bytes (bitset: 3328 bits)
 *   Total: 744 bytes (block=128, page=64)
 * 
 * Value distribution:
 *   Value   Codepoints    Span
 *   Yes           1219    U+231A..U+1FAF8
 *   No         1112893    U+0000..U+10FFFF
 *   ----       1114112 (universe)
 */

static const uint8_t emoji_ucd_is_presentation_idx0[136] = {
  0, 1, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 2,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0
};

static const uint8_t emoji_ucd_is_presentation_idx1[192] = {
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  1,  2,
   0,  0,  0,  3,  4,  5,  6,  7,
   0,  0,  0,  0,  0,  0,  8,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0,
   9, 10,  0, 11, 12,  0, 13, 14,
  15, 16, 17, 18, 19, 20,  0, 21,
   0,  0, 22, 23, 24, 25,  0,  0,
   0,  0,  0,  0,  0,  0,  0,  0
};

static const uint8_t emoji_ucd_is_presentation_data[416] = {
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,  12,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,  30,   9,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,  96,
    0,   0,  48,   0,   0,   0,   0,   0,
    0, 255,  15,   0,   0,   0,   0, 128,
    0,   0,   8,   0,   2,  12,   0,  96,
   48,  64,  16,   0,   0,   4,  44,  36,
   32,  12,   0,   0,   0,   1,   0,   0,
    0,  80, 184,   0,   0,   0,   0,   0,
    0,   0, 224,   0,   0,   0,   1, 128,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,  24,   0,   0,   0,   0,
    0,   0,  33,   0,   0,   0,   0,   0,
   16,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,
    0, 128,   0,   0,   0,   0,   0,   0,
    0,  64, 254,   7,   0,   0,   0,   0,
    0,   0,   0,   0, 192, 255, 255, 255,
    2,   0,   0,   4,   0, 128, 124,   7,
    0,   0,   3,   0,   0,   0,   0,   0,
  255, 255, 255, 255,   1, 224, 191, 255,
  255, 255, 255, 255, 255, 255, 255, 223,
  255, 255,  15,   0, 255, 255, 255, 255,
  255, 135,  15,   0, 255, 255,  17, 255,
  255, 255, 255, 255, 255, 255, 255, 127,
  253, 255, 255, 255, 255, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 255, 159,
  255, 255, 255, 255, 255, 255, 255,  63,
    0, 120, 255, 255, 255,   0,   0,   4,
    0,   0,  96,   0,  16,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0, 248,
  255, 255, 255, 255, 255, 255, 255, 255,
  255, 255,   0,   0,   0,   0,   0,   0,
  255, 255, 255, 255, 255, 255, 255, 255,
   63,  16, 231, 241,   0,  24, 240,  31,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0, 255,  15,   1,   0,
    0, 240, 255, 255, 255, 255, 255, 247,
  191, 255, 255, 255, 255, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 255, 255,
  255, 255, 255, 255, 255, 255, 255, 255,
    0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0, 255,  31,
  255, 199, 255, 255, 255, 255, 255, 255,
  127, 225, 255, 159, 255, 135, 255,   1
};

#define EMOJI_UCD_IS_PRESENTATION_INDEX_SHIFT 8
#define EMOJI_UCD_IS_PRESENTATION_INDEX_MASK ((1u << EMOJI_UCD_IS_PRESENTATION_INDEX_SHIFT) - 1)
#define EMOJI_UCD_IS_PRESENTATION_BLOCK_SIZE  128
#define EMOJI_UCD_IS_PRESENTATION_BLOCK_SHIFT 7
#define EMOJI_UCD_IS_PRESENTATION_BLOCK_MASK (EMOJI_UCD_IS_PRESENTATION_BLOCK_SIZE - 1)
#define EMOJI_UCD_IS_PRESENTATION_PAGE_SIZE   64
#define EMOJI_UCD_IS_PRESENTATION_PAGE_SHIFT  6
#define EMOJI_UCD_IS_PRESENTATION_PAGE_MASK  (EMOJI_UCD_IS_PRESENTATION_PAGE_SIZE - 1)

static inline bool emoji_ucd_is_presentation(uint32_t cp) {
  uint32_t page = (cp >> (EMOJI_UCD_IS_PRESENTATION_BLOCK_SHIFT + EMOJI_UCD_IS_PRESENTATION_PAGE_SHIFT)) & EMOJI_UCD_IS_PRESENTATION_INDEX_MASK;
  uint32_t off1 = (cp >> EMOJI_UCD_IS_PRESENTATION_BLOCK_SHIFT) & EMOJI_UCD_IS_PRESENTATION_PAGE_MASK;
  uint32_t off2 = cp & EMOJI_UCD_IS_PRESENTATION_BLOCK_MASK;

  uint32_t i0 = emoji_ucd_is_presentation_idx0[page];
  uint32_t i1 = emoji_ucd_is_presentation_idx1[(i0 << EMOJI_UCD_IS_PRESENTATION_PAGE_SHIFT) + off1];

  uint32_t data_idx = (i1 << EMOJI_UCD_IS_PRESENTATION_BLOCK_SHIFT) + off2;
  return (emoji_ucd_is_presentation_data[data_idx >> 3] >> (data_idx & 7)) & 1;
}

#ifdef __cplusplus
}
#endif
#endif // EMOJI_UCD_H
